
#This is a setting for language.
[language]
    
    #param list : [ kJapan , kEnglish ]
    language_country = "kEnglish"
    
#This is a setting for sound and volume.
[sound]
    
    #The value range is from 0 to 100.
    bgm_volume = 50
    
    #The value range is from 0 to 100.
    sound_volume = 30
    
